-- 清理所有旧表
DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS material_usage CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS process_execution CASCADE;
DROP TABLE IF EXISTS process_nodes CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS users CASCADE;
